openapi: 3.0.0
info:
  title: API-Animal
  deion: Essa API fornece recursos para persistência de animal em um banco de dados
  contact:
    email: clevertonmarcelo6@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:8081/api
    deion: rota para API
paths:
  /animal:
    post:
      summary: Cadastro de animal
      deion: Essa rota irá cadastrar um animal
      tags:
        - animal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/animal'
            examples:
              animal:
                value:
                  nome: Carme
                  nomeDoProprietario: Cosmo
                  endereco: tangamandapio
                  tipo: jaiminho
                  raca: madruga
                  imagem: Pig.jpg
      responses:
        '200':
          deion: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/animal'
  /animal/{id}:
    get:
      summary: Busca animal pelo Id
      deion: Essa rota irá buscar por um animal pelo ID.
      tags:
        - animal
      parameters:
        - name: id
          in: path
          deion: ID da animal no banco de dados.
          required: true
      responses:
        '200':
          deion: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Animal'
components:
  schemas:
    animal:
      type: object
      properties:
        nome:
          type: string
        nomeDoProprietario:
          type: string
        endereco:
          type: string
        tipo:
          type: string
        raca:
          type: string
        imagem:
          type: file
